### ISSUE TITLE
Include LightStorage  with the package

### ISSUE THREAD

**Issue by Demoevery** [poirierlouis/file_system_access_api#10]
Until the issue is fixed for the usecase of saving directory please include the example LightStorage with this package.

**Comment by poirierlouis** [comment]
This package is only meant to provide FileSystemAccess API with Dart types.
LightStorage is only an example to show how you can workaround the current issue. It doesn't make sense to include it in the package.
However, you are free to use the content of LightStorage in your own implementation.
