### ISSUE TITLE
Request for an example of how to read a file FileSystemFileHandle using FileReader

### ISSUE THREAD

**Issue by tomekit** [poirierlouis/file_system_access_api#3]
Hi, 
I am trying to get the list of files from a folder using: `showDirectoryPicker`. I've ended up having a list of `FileSystemHandle` / `FileSystemFileHandle`.

I couldn't easily workout how to use `FileReader` properly on that case. In this package documentation there is a comment (https://pub.dev/packages/file_system_access_api#open-files):
 `You can read content of a File using a FileReader, like any other File coming from 'dart:html'`. 

so I've ended up having a handle and the reader:
```dart
final file = await handle.getFile();
FileReader fr = new FileReader();
```
I would appreciate if you could share an example how to read the file. Thanks !

**Comment by poirierlouis** [comment]
Hi,

The usage of `FileReader` is out of the scope of this package, this is why I only let a comment in the example. You can found examples by searching for it on the web, don't forget the official documentation. Nonetheless, here is a possible usage (not tested):
```dart
void readFile(final handle) async {
  final file = await handle.getFile();
  final reader = FileReader();

  reader.readAsText(file);
  await reader.onLoadEnd.first;
  final data = reader.result as String;

  print(data);
}
```
