### ISSUE TITLE
How to save and read with OPFS?

### ISSUE THREAD

**Issue by gokhanmeteerturk** [poirierlouis/file_system_access_api#4]
Is there an example showing:
How to check if opfs is supported.
How to save a file (image/vide) to with a specific handle using opfs.
How to read a file with that specific handle using opfs.

**Comment by poirierlouis** [comment]
> How to check if opfs is supported.

You can test whether File System Access Api is supported (see [here](https://github.com/poirierlouis/file_system_access_api#is-browser-supported)), it should be enough to account for OPFS. OPFS is supported across [major browsers](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system#browser_compatibility).

> How to save a file (image/vide) to with a specific handle using opfs.

You shall first acquire a handle from your OPFS root directory ([get handle](https://github.com/poirierlouis/file_system_access_api/blob/2073a12a2b2e22dd3450bc12a2b5c1de27e5fcbd/example/example.dart#L66)). Then you can create a WritableStream to write any type of data you want in the file ([write data](https://github.com/poirierlouis/file_system_access_api/blob/2073a12a2b2e22dd3450bc12a2b5c1de27e5fcbd/example/example.dart#L35)). You can write data with three different types: [Uint8List](https://github.com/poirierlouis/file_system_access_api/blob/2073a12a2b2e22dd3450bc12a2b5c1de27e5fcbd/lib/src/api/file_system_file_handle.dart#L175), String or Blob.

> How to read a file with that specific handle using opfs.

You can read a file like mentioned [here](https://github.com/poirierlouis/file_system_access_api/blob/2073a12a2b2e22dd3450bc12a2b5c1de27e5fcbd/example/example.dart#L28). You will need a `FileReader` to do so. Which is out of the scope of this library, and thus not explained (there is already enough on the web about reading a `File`).
Also, see this issue #3.

Maybe I should explicitly inform users about `writeAsArrayBuffer`, `writeAsBlob`? Let me know if this was the missing part in documentation / example to connect the dots.
